pipeline {
    agent {
        label 'ec2-static'
    }
    
    options {
        buildDiscarder(logRotator(numToKeepStr: '10'))
        disableConcurrentBuilds()
    }
    
    stages {
        
        stage('Check Versioning') {
            steps {
                script {
                    def hasChanges = checkS3Version()
                    if (!hasChanges) {
                        currentBuild.result = 'SUCCESS'
                        echo "No version changes detected. Skipping pipeline."
                        env.SKIP_PIPELINE = 'true'
                    } else {
                        echo "Version change detected. Updating S3 version bucket immediately."
                        updateS3Version()
                    }
                }
            }
        }
        
        stage('Build & Test') {
            when {
                allOf {
                    branch 'dev'
                    environment name: 'SKIP_PIPELINE', value: ''
                }
            }
            steps {
                script {
                    buildApp()
                    unitTests()
                    checkJacocoReport()
                    stashMavenBuildOutput()
                }
            }
        }

        stage('Code Analysis') {
            agent {
                label 'master'
            }
            when {
                allOf {
                    branch 'dev'
                    environment name: 'SKIP_PIPELINE', value: ''
                }
            }
            steps {
                script {
                    restoreMavenBuildOutput()
                    sonarScan()
                    qualityGate()
                }
            }
        }      
        stage('Integration Test') {
            when {
                allOf {
                    branch 'dev'
                    environment name: 'SKIP_PIPELINE', value: ''
                    not { changeRequest() }
                }
            }
            steps {
                script {
                    integrationTests()
                }
            }
        } 
        stage('Security Scanning') {
            when {
                environment name: 'SKIP_PIPELINE', value: ''
            }
            steps {
                script {
                    dependencyScan()
                }
            }
        }
 
        stage('Package Artifact') {
            when {
                allOf {
                    branch 'dev'
                    environment name: 'SKIP_PIPELINE', value: ''
                    not { changeRequest() }
                }
            }
            steps {
                script {
                    packageArtifact()
                }
            }
        }
        
        stage('Containerize & Scan (Dev Only)') {
            when {
                allOf {
                    branch 'dev'
                    environment name: 'SKIP_PIPELINE', value: ''
                    not { changeRequest() }
                }
            }
            steps {
                script {
                    buildContainer()
                    imageVulnerabilityScan()
                }
            }
        }
        
        stage('Publish Artifacts') {
            when {
                allOf {
                    environment name: 'SKIP_PIPELINE', value: ''
                    not { changeRequest() }
                }
            }
            steps {
                script {
                    pushToECR()
                    generateSBOM()
                }
            }
        }
        
    
        /*
        stage('Promote & Merge Dev -> Test') {
            when {
                branch 'dev'
                environment name: 'SKIP_PIPELINE', value: ''
                !changeRequest() 
            }
            steps {
                script {
                    echo "Dev Pipeline successful! Promoting code to test branch via git merge..."
                    autoMerge(targetBranch: 'test')
                }
            }
        }
        */
        
        /*
        stage('Approval & Merge Test -> Prod') {
            when {
                branch 'test'
                environment name: 'SKIP_PIPELINE', value: ''
                !changeRequest() 
            }
            steps {
                script {
                    validateExitCriteria()
                    timeout(time: 24, unit: 'HOURS') {
                        input message: 'READY FOR PROD: Approve merging these changes into the prod branch?', submitter: 'admin-group'
                    }
                    echo "Approval granted. Promoting code to prod branch via git merge..."
                    autoMerge(targetBranch: 'prod')
                }
            }
        }*/
        
    }
}